# @package _group_

type: robot
path: assets/robots/unitree/g1/g1_dex3_rev_1_0.xml

joints:
  left_hip_pitch_joint:
    control_type: torque
    stiffness: 150.0
    damping: 2.0
    velocity_limit: 32.0
    torque_limit: 88.0
    position_limit: [-2.5307, 2.8798]
    default_position: -0.1
    properties:
      armature: 0.01
      frictionloss: 0.2
  left_hip_roll_joint:
    control_type: torque
    stiffness: 150.0
    damping: 2.0
    velocity_limit: 20.0
    torque_limit: 139.0
    position_limit: [-0.5236, 2.9671]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.2
  left_hip_yaw_joint:
    control_type: torque
    stiffness: 150.0
    damping: 2.0
    velocity_limit: 32.0
    torque_limit: 88.0
    position_limit: [-2.7576, 2.7576]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.2
  left_knee_joint:
    control_type: torque
    stiffness: 300.0
    damping: 4.0
    velocity_limit: 20.0
    torque_limit: 139.0
    position_limit: [-0.087267, 2.8798]
    default_position: 0.3
    properties:
      armature: 0.01
      frictionloss: 0.2
  left_ankle_pitch_joint:
    control_type: torque
    stiffness: 40.0
    damping: 2.0
    velocity_limit: 37.0
    torque_limit: 25.0
    position_limit: [-0.87267, 0.5236]
    default_position: -0.2
    properties:
      armature: 0.01
      frictionloss: 0.2
  left_ankle_roll_joint:
    control_type: torque
    stiffness: 40.0
    damping: 2.0
    velocity_limit: 37.0
    torque_limit: 25.0
    position_limit: [-0.2618, 0.2618]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.2
  right_hip_pitch_joint:
    control_type: torque
    stiffness: 150.0
    damping: 2.0
    velocity_limit: 32.0
    torque_limit: 88.0
    position_limit: [-2.5307, 2.8798]
    default_position: -0.1
    properties:
      armature: 0.01
      frictionloss: 0.2
  right_hip_roll_joint:
    control_type: torque
    stiffness: 150.0
    damping: 2.0
    velocity_limit: 20.0
    torque_limit: 139.0
    position_limit: [-2.9671, 0.5236]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.2
  right_hip_yaw_joint:
    control_type: torque
    stiffness: 150.0
    damping: 2.0
    velocity_limit: 32.0
    torque_limit: 88.0
    position_limit: [-2.7576, 2.7576]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.2
  right_knee_joint:
    control_type: torque
    stiffness: 200.0
    damping: 4.0
    velocity_limit: 20.0
    torque_limit: 139.0
    position_limit: [-0.087267, 2.8798]
    default_position: 0.3
    properties:
      armature: 0.01
      frictionloss: 0.2
  right_ankle_pitch_joint:
    control_type: torque
    stiffness: 40.0
    damping: 2.0
    velocity_limit: 37.0
    torque_limit: 25.0
    position_limit: [-0.87267, 0.5236]
    default_position: -0.2
    properties:
      armature: 0.01
      frictionloss: 0.2
  right_ankle_roll_joint:
    control_type: torque
    stiffness: 40.0
    damping: 2.0
    velocity_limit: 37.0
    torque_limit: 25.0
    position_limit: [-0.2618, 0.2618]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.2
  waist_yaw_joint:
    control_type: torque
    stiffness: 250.0
    damping: 5.0
    velocity_limit: 32.0
    torque_limit: 88.0
    position_limit: [-2.618, 2.618]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.2
  waist_roll_joint:
    control_type: torque
    stiffness: 250.0
    damping: 5.0
    velocity_limit: 37.0
    torque_limit: 25.0
    position_limit: [-0.52, 0.52]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.2
  waist_pitch_joint:
    control_type: torque
    stiffness: 250.0
    damping: 5.0
    velocity_limit: 37.0
    torque_limit: 25.0
    position_limit: [-0.52, 0.52]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.2
  left_shoulder_pitch_joint:
    control_type: torque
    stiffness: 100.0
    damping: 5.0
    velocity_limit: 37.0
    torque_limit: 25.0
    position_limit: [-3.0892, 2.6704]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.2
  left_shoulder_roll_joint:
    control_type: torque
    stiffness: 100.0
    damping: 5.0
    velocity_limit: 37.0
    torque_limit: 25.0
    position_limit: [-1.5882, 2.2515]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.2
  left_shoulder_yaw_joint:
    control_type: torque
    stiffness: 40.0
    damping: 2.0
    velocity_limit: 37.0
    torque_limit: 25.0
    position_limit: [-2.618, 2.618]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.2
  left_elbow_joint:
    control_type: torque
    stiffness: 40.0
    damping: 2.0
    velocity_limit: 37.0
    torque_limit: 25.0
    position_limit: [-1.0472, 2.0944]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.2
  left_wrist_roll_joint:
    control_type: torque
    stiffness: 20.0
    damping: 2.0
    velocity_limit: 37.0
    torque_limit: 25.0
    position_limit: [-1.972222054, 1.972222054]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.1
  left_wrist_pitch_joint:
    control_type: torque
    stiffness: 20.0
    damping: 2.0
    velocity_limit: 22.0
    torque_limit: 5.0
    position_limit: [-1.614429558, 1.614429558]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.1
  left_wrist_yaw_joint:
    control_type: torque
    stiffness: 20.0
    damping: 2.0
    velocity_limit: 22.0
    torque_limit: 5.0
    position_limit: [-1.614429558, 1.614429558]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.1
  left_hand_index_0_joint:
    control_type: position # torque
    stiffness: 5.0
    damping: 1.0
    velocity_limit: 1e15
    torque_limit: 1.4
    position_limit: [-1.57079632, 0.0]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.01
  left_hand_index_1_joint:
    control_type: position #torque
    stiffness: 5.0
    damping: 1.0
    velocity_limit: 1e15
    torque_limit: 1.4
    position_limit: [-1.74532925, 0.0]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.01
  left_hand_middle_0_joint:
    control_type: position # torque
    stiffness: 5.0
    damping: 1.0
    velocity_limit: 1e15
    torque_limit: 1.4
    position_limit: [-1.57079632, 0.0]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.01
  left_hand_middle_1_joint:
    control_type: position #torque
    stiffness: 5.0
    damping: 1.0
    velocity_limit: 1e15
    torque_limit: 1.4
    position_limit: [-1.74532925, 0.0]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.01
  left_hand_thumb_0_joint:
    control_type: position #torque
    stiffness: 5.0
    damping: 1.0
    velocity_limit: 1e15
    torque_limit: 2.45
    position_limit: [-1.04719755, 1.04719755]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.01
  left_hand_thumb_1_joint:
    control_type: position #torque
    stiffness: 5.0
    damping: 1.0
    velocity_limit: 1e15
    torque_limit: 1.4
    position_limit: [-0.724312, 1.04719755]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.01
  left_hand_thumb_2_joint:
    control_type: position # torque
    stiffness: 5.0
    damping: 1.0
    velocity_limit: 1e15
    torque_limit: 1.4
    position_limit: [0.0, 1.74532925]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.01
  right_shoulder_pitch_joint:
    control_type: torque
    stiffness: 100.0
    damping: 5.0
    velocity_limit: 37.0
    torque_limit: 25.0
    position_limit: [-3.0892, 2.6704]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.2
  right_shoulder_roll_joint:
    control_type: torque
    stiffness: 100.0
    damping: 5.0
    velocity_limit: 37.0
    torque_limit: 25.0
    position_limit: [-2.2515, 1.5882]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.2
  right_shoulder_yaw_joint:
    control_type: torque
    stiffness: 40.0
    damping: 2.0
    velocity_limit: 37.0
    torque_limit: 25.0
    position_limit: [-2.618, 2.618]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.2
  right_elbow_joint:
    control_type: torque
    stiffness: 40.0
    damping: 2.0
    velocity_limit: 37.0
    torque_limit: 25.0
    position_limit: [-1.0472, 2.0944]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.2
  right_wrist_roll_joint:
    control_type: torque
    stiffness: 20.0
    damping: 2.0
    velocity_limit: 37.0
    torque_limit: 25.0
    position_limit: [-1.972222054, 1.972222054]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.1
  right_wrist_pitch_joint:
    control_type: torque
    stiffness: 20.0
    damping: 2.0
    velocity_limit: 22.0
    torque_limit: 5.0
    position_limit: [-1.614429558, 1.614429558]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.1
  right_wrist_yaw_joint:
    control_type: torque
    stiffness: 20.0
    damping: 2.0
    velocity_limit: 22.0
    torque_limit: 5.0
    position_limit: [-1.614429558, 1.614429558]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.1
  right_hand_index_0_joint:
    control_type: position # torque
    stiffness: 5.0
    damping: 1.0
    velocity_limit: 1e15
    torque_limit: 1.4
    position_limit: [0.0, 1.57079632]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.01
  right_hand_index_1_joint:
    control_type: position # torque
    stiffness: 5.0
    damping: 1.0
    velocity_limit: 1e15
    torque_limit: 1.4
    position_limit: [0.0, 1.74532925]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.01
  right_hand_middle_0_joint:
    control_type: position # torque
    stiffness: 5.0
    damping: 1.0
    velocity_limit: 1e15
    torque_limit: 1.4
    position_limit: [0.0, 1.57079632]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.01
  right_hand_middle_1_joint:
    control_type: position # torque
    stiffness: 5.0
    damping: 1.0
    velocity_limit: 1e15
    torque_limit: 1.4
    position_limit: [0.0, 1.74532925]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.01
  right_hand_thumb_0_joint:
    control_type: position # torque
    stiffness: 5.0
    damping: 1.0
    velocity_limit: 1e15
    torque_limit: 2.45
    position_limit: [-1.04719755, 1.04719755]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.01
  right_hand_thumb_1_joint:
    control_type: position # torque
    stiffness: 5.0
    damping: 1.0
    velocity_limit: 1e15
    torque_limit: 1.4
    # position_limit: [-1.04719755, 1.04719755]
    position_limit: [-1.04719755, 0.61086523]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.01
  right_hand_thumb_2_joint:
    control_type: position # torque
    stiffness: 5.0
    damping: 1.0
    velocity_limit: 1e15
    torque_limit: 1.4
    position_limit: [-1.74532925, 0.0]
    default_position: 0.0
    properties:
      armature: 0.01
      frictionloss: 0.01

sensors:
  # rs_camera:
  #   type: camera
  #   width: 640
  #   height: 480
  #   freq: 30.0
  #   vertical_fov: 59.
  #   mount_to: torso_link
  #   pose: [0.07555294, 0.02579919, 0.49719054, 0.67876761, 0.20864099, -0.20567003, -0.67338199]
  # rs_camera:
  #   type: camera
  #   width: 640
  #   height: 480
  #   freq: 30.0
  #   vertical_fov: 40.
  #   mount_to: torso_link
  #   pose: [0.07555294, 0.02579919, 0.49719054, 0.67876761, 0.20864099, -0.20567003, -0.67338199]
  rs_camera: # actually oak camera
    type: camera
    width: 640
    height: 480
    freq: 30.0
    vertical_fov: 79.5
    mount_to: torso_link
    # position: [0.10209156, -0.00937542, 0.42446595]
    pose:
      [
        0.10209156,
        -0.00937542,
        0.42446595,
        0.64367383,
        0.26523914,
        -0.27106013,
        -0.66472446,
      ]
  tpp_camera:
    type: camera
    width: 640
    height: 480
    freq: 30.0
    vertical_fov: 60.
    mount_to: pelvis
    pose:
      [-1.131, -0.626, 0.481, 0.67953146, 0.46872971, -0.3204774, -0.46456828]

properties:
  fix_base_link: false
  # imu: it is built in the xml model
