# Simulator configuration
backend: mujoco
sim:
  dt: 0.002
  render_interval: 10
  gravity: [0.0, 0.0, -9.81]
  headless: false
  device: "cpu"
  backend_spec:
    render:
      mode: mjviewer
      camera: g1/tpp_camera
      width: 640
      height: 480

scene:
  terrain:
    type: plane
    properties:
      geom:
        ground_plane:
          friction: [1.0, 0.005, 0.0001]
          solimp: [0.9, 0.95, 0.001, 0.5, 2.0]
          solref: [0.02, 1.0]
  visual:
    light:
      diffuse: [0.8, 0.8, 0.8]
      ambient: [0.2, 0.2, 0.2]
      specular: [1.0, 1.0, 1.0]
    properties:
      rgba:
        haze: [0.15, 0.25, 0.35, 1]

extras:
  decimation: 10
  max_episode_steps: 1000
