# Simulator configuration
backend: mujoco
sim:
  dt: 0.005
  render_interval: 10
  gravity: [0.0, 0.0, -9.81]
  headless: false
  device: "cpu"
spec:
  mujoco:
    render:
      mode: mjviewer
      camera: g1/tpp_camera
      width: 640
      height: 480

extras:
  decimation: 4
  max_episode_steps: 10000

scene:
  terrain:
    type: plane
    properties:
      geom:
        size: [0, 0, 0.01]
        contype: 1
        conaffinity: 0
        priority: 1
        friction: [0.6, 0.6, 0.6]
        condim: 3
      material:
        reflectance: 0
  visual:
    light:
      diffuse: [0.8, 0.8, 0.8]
      ambient: [0.2, 0.2, 0.2]
      specular: [1.0, 1.0, 1.0]
    properties:
      rgba:
        haze: [0.15, 0.25, 0.35, 1]
