# @package scene.robots

g1:
  path: "assets/unitree/g1/g1_dex3_rev_1_0.xml"
  initial_position: [0.0, 0.0, 0.0]
  initial_orientation: [0.0, 0.0, 0.0, 1.0]
  joints:
    joint1:
      control_type: position
      stiffness: 100.0
      damping: 1.0
      velocity_limit: 5.0
      torque_limit: 10.0
      position_limit: [-1.57, 1.57]
  sensors:
    camera:
      type: rgb
      position: [0.1, 0.0, 0.2]
      orientation: [0.0, 0.0, 0.0, 1.0]
      fov: 90
      resolution: [640, 480]
    # imu: it is built in the xml model
