# @package scene.robots

g1:
  path: "assets/unitree/g1/g1_dex3_rev_1_0.xml"
  initial_position: [0.0, 0.0, 0.0]
  initial_orientation: [0.0, 0.0, 0.0, 1.0]
  joints:
    joint1:
      control_type: position
      stiffness: 100.0
      damping: 1.0
      velocity_limit: 5.0
      torque_limit: 10.0
      position_limit: [-1.57, 1.57]
  sensors:
    head_camera:
      type: camera
      width: 640
      height: 480
      freq: 50
      mount_to: g1
      mount_link: head_link
    # imu: it is built in the xml model
