# @package _global_

# Default configuration for robot simulation using Hydra
# Override with: python scripts/run_sim.py backends=isaac robots=h1 objects=sphere

# Hydra runtime configuration
hydra:
  run:
    dir: outputs/debug
  sweep:
    dir: outputs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: false

defaults:
  - _self_
  - /objects/robots/unitree/g1_dex3.yaml@scene.objects.g1
  - /objects/builtin/sphere.yaml@scene.objects.sphere

backend: mujoco

# simulator settings
sim:
  dt: 0.002
  render_interval: 10
  gravity: [0.0, 0.0, -9.81]
  headless: false
  device: "cpu"
  num_envs: 1
  backend_spec:
    render:
      mode: opencv # or opencv
      camera: g1/tpp_camera
      width: 640
      height: 480

extras:
  max_episode_steps: 1024
  decimation: 10

scene:
  path: assets/scenes/gear_lab/gear_lab.xml
  objects:
    apple:
      path: assets/objects/apple_0/model.xml
      pose: [0.4, 0.0, 0.7, 1, 0, 0, 0] # xyz qw
    plate:
      path: assets/objects/plate_1/model.xml
      pose: [0.4, 1.2, 0.7, 1, 0, 0, 0]
    object_table:
      path: assets/objects/lab_table/model.xml
      pose: [0.5, 0.0, 0.0, 0.707, 0.0, 0.0, 0.707]
    target_table:
      path: assets/objects/lab_table/model.xml
      pose: [0.5, 1.2, 0.0, 0.707, 0.0, 0.0, 0.707]
    g1:
      pose: [0.0, 0.0, 0.793, 1.0, 0.0, 0.0, 0.0]

  # Example of adding a simple plane terrain
  # terrain:
  #   type: plane
