# @package _global_

# Default configuration for robot simulation using Hydra
# Override with: python scripts/run_sim.py backends=isaac robots=h1 objects=sphere

defaults:
  - _self_
  - backends: mujoco.yaml
  - objects: [g1.yaml, sphere.yaml] # load configs/robots/g1.yaml
  # - objects: g1.yaml
  # - objects: sphere.yaml

# Hydra runtime configuration
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: false

scene:
  path: assets/scenes/gear_lab/gear_lab.xml
  # terrain:
  #   type: plane