# Hydra runtime configuration
hydra:
  run:
    dir: outputs/debug
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: false

# Configuration group for environment configuration

# Default configurations to compose the full configuration
defaults:
  - _self_
  - /maps.yaml@env_config.maps
  - /robots/g1_dex3_gr00t.yaml@env_config.scene.objects.g1

task: Gr00tPickAndPlace-v0

# Task specific parameters
params:
  object_name: apple
  target_name: plate
  success_threshold: 0.05

# Environment configuration
env_config:
  scene:
    path: ${root:}/assets/scenes/gear_lab/gear_lab.xml
    # terrain:
    #   type: plane
    objects:
      apple:
        path: ${root:}/assets/objects/apple_0/model.xml
        # initial_position: [0.4, 0.0, 0.684446]
        initial_position: [0.4, 0.0, 0.73]
        # initial_orientation: [1, 0.0, 0.0, 0] # [w, x, y, z]
      plate:
        path: ${root:}/assets/objects/plate_1/model.xml
        initial_position: [0.4, 1.2, 0.7]
      object_table:
        path: ${root:}/assets/objects/lab_table/model.xml
        initial_position: [0.5, 0.0, 0.0]
        initial_orientation: [0.707, 0.0, 0.0, 0.707]
      target_table:
        path: ${root:}/assets/objects/lab_table/model.xml
        initial_position: [0.5, 1.2, 0.0]
        initial_orientation: [0.707, 0.0, 0.0, 0.707]
      g1:
        initial_position: [-0.5, 0.0, 0.78]
