# @package _global_

# Hydra runtime configuration
hydra:
  run:
    dir: outputs/debug
  sweep:
    dir: outputs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: false

# Configuration group for environment configuration

# Default configurations to compose the full configuration
defaults:
  - _self_
  - /default/simulator.yaml@environment.simulator
  - /default/modality.yaml@environment.maps
  - /default/controller.yaml@environment.controller
  - /robots/g1_dex3_gr00t.yaml@environment.simulator.scene.objects.g1

task: Gr00tPickAndPlace-v0

# Task specific parameters
params:
  object_name: apple
  target_name: plate
  success_threshold: 0.05

# Rewrite Environment config to build the task-specific simulator setup
environment:
  simulator:
    scene:
      path: assets/scenes/gear_lab/gear_lab.xml
      # terrain:
      #   type: plane
      objects:
        apple:
          path: assets/objects/apple_0/model.xml
          # initial_state: [0.4, 0.0, 0.684446]
          initial_state: 
            position: [0.4, 0.0, 0.72]
          #  orientation: [1, 0.0, 0.0, 0] # [w, x, y, z]
        plate:
          path: assets/objects/plate_1/model.xml
          initial_state: 
            position: [0.3, 1.2, 0.72]
        object_table:
          path: assets/objects/lab_table/model.xml
          initial_state: 
            position: [0.5, 0.0, 0.0] # [0.0, 0.0, 0.684446]
            orientation: [0.707, 0.0, 0.0, 0.707]
        target_table:
          path: assets/objects/lab_table/model.xml
          initial_state: 
            position: [0.5, 1.2, 0.0]
            orientation: [0.707, 0.0, 0.0, 0.707]
        g1:
          initial_state: 
            position: [0.05, 0.05, 0.74]