# @package _global_

# Hydra runtime configuration
hydra:
  run:
    dir: outputs/debug
  sweep:
    dir: outputs/multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}
  job:
    chdir: false

# Configuration group for environment configuration

# Default configurations to compose the full configuration
defaults:
  - _self_
  - /default/simulator.yaml@simulator
  - /default/modality.yaml@maps
  - /default/policy.yaml@maps.policy
  - /robots/g1_dex3_gr00t.yaml@simulator.scene.objects.unitree_g1_with_hands

task: Gr00tStack-v0

# Task specific parameters
params:
  object_name: red_cube
  target_name: yellow_cube
  success_threshold: 0.05

# Rewrite Environment config to build the task-specific simulator setup
simulator:
  scene:
    path: assets/scenes/gear_lab/gear_lab.xml
    objects:
      red_cube:
        type: cube
        pose: [0.3, -0.1, 0.72, 1, 0.0, 0.0, 0] # [w, x, y, z]
        properties:
          size: [0.05, 0.05, 0.05]
          color: [1.0, 0.0, 0.0]
      yellow_cube:
        type: cube
        pose: [0.3, 0.1, 0.72, 1, 0.0, 0.0, 0]
        properties:
          size: [0.05, 0.05, 0.05]
          color: [1.0, 1.0, 0.0]
      table:
        path: assets/objects/lab_table/model.xml
        pose: [0.5, 0.0, 0.0, 0.707, 0.0, 0.0, 0.707]
      unitree_g1_with_hands:
        pose: [0.0, 0.0, 0.793, 1, 0.0, 0.0, 0.0]
