# Environment configuration

defaults:
  - _self_
  - /configs/robots/g1_dex3_gr00t.yaml@scene.objects.g1

backend: mujoco
sim:
  dt: 0.002
  render_interval: 10
  gravity: [0.0, 0.0, -9.81]
  headless: false
  device: "cpu"
extras:
  decimation: 10
  max_episode_steps: 1000
